Repository YesunPark/cafe-bom, pull requests merged in 2023-09, with the labels that each got.

#36 Feat: 주문 저장(생성) 기능 구현
  src/main/java/com/zerobase/cafebom/cart/repository/CartRepository.java
  src/main/java/com/zerobase/cafebom/cartoption/domain/entity/CartOption.java
  src/main/java/com/zerobase/cafebom/cartoption/repository/CartOptionRepository.java
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/orders/controller/.gitkeep
  src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
  src/main/java/com/zerobase/cafebom/orders/controller/form/.gitkeep
  src/main/java/com/zerobase/cafebom/orders/controller/form/OrdersAddForm.java
  src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
  src/main/java/com/zerobase/cafebom/orders/service/.gitkeep
  src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
  src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersAddDto.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersServiceTest.java
Labels: new feature, 빠른 리뷰 요청

#46 Feat : 관리자 상품 카테고리 등록 기능 추가
  src/main/java/com/zerobase/cafebom/productcategory/controller/.gitkeep
  src/main/java/com/zerobase/cafebom/productcategory/controller/ProductCategoryController.java
  src/main/java/com/zerobase/cafebom/productcategory/controller/form/.gitkeep
  src/main/java/com/zerobase/cafebom/productcategory/controller/form/ProductCategoryForm.java
  src/main/java/com/zerobase/cafebom/productcategory/domain/.gitkeep
  src/main/java/com/zerobase/cafebom/productcategory/service/.gitkeep
  src/main/java/com/zerobase/cafebom/productcategory/service/ProductCategoryService.java
  src/main/java/com/zerobase/cafebom/productcategory/service/ProductCategoryServiceImpl.java
  src/main/java/com/zerobase/cafebom/productcategory/service/dto/.gitkeep
  src/main/java/com/zerobase/cafebom/productcategory/service/dto/ProductCategoryDto.java
Labels: new feature, 리뷰 요청

#47 Feat : 관리자 상품 카테고리 수정 기능 추가
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/productcategory/controller/ProductCategoryController.java
  src/main/java/com/zerobase/cafebom/productcategory/controller/form/ProductCategoryForm.java
  src/main/java/com/zerobase/cafebom/productcategory/domain/entity/ProductCategory.java
  src/main/java/com/zerobase/cafebom/productcategory/service/ProductCategoryService.java
  src/main/java/com/zerobase/cafebom/productcategory/service/ProductCategoryServiceImpl.java
  src/main/java/com/zerobase/cafebom/productcategory/service/dto/ProductCategoryDto.java
Labels: new feature, 리뷰 요청

#40 Feat : 관리자 Option 등록 기능 생성
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/option/controller/.gitkeep
  src/main/java/com/zerobase/cafebom/option/controller/OptionController.java
  src/main/java/com/zerobase/cafebom/option/controller/form/.gitkeep
  src/main/java/com/zerobase/cafebom/option/controller/form/OptionAddForm.java
  src/main/java/com/zerobase/cafebom/option/domain/.gitkeep
  src/main/java/com/zerobase/cafebom/option/service/.gitkeep
  src/main/java/com/zerobase/cafebom/option/service/OptionService.java
  src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
  src/main/java/com/zerobase/cafebom/option/service/dto/.gitkeep
  src/main/java/com/zerobase/cafebom/option/service/dto/OptionAddDto.java
Labels: new feature, 리뷰 요청

#43 Feat: 관리자 Option 수정 기능 추가
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/option/controller/OptionController.java
  src/main/java/com/zerobase/cafebom/option/controller/form/OptionModifyForm.java
  src/main/java/com/zerobase/cafebom/option/domain/entity/Option.java
  src/main/java/com/zerobase/cafebom/option/service/OptionService.java
  src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
  src/main/java/com/zerobase/cafebom/option/service/dto/OptionModifyDto.java
Labels: new feature, 리뷰 요청

#44 Feat : 관리자 Option 조회, 삭제기능 추가
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/option/controller/OptionController.java
  src/main/java/com/zerobase/cafebom/option/controller/form/OptionAddForm.java
  src/main/java/com/zerobase/cafebom/option/controller/form/OptionForm.java
  src/main/java/com/zerobase/cafebom/option/controller/form/OptionModifyForm.java
  src/main/java/com/zerobase/cafebom/option/service/OptionService.java
  src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
  src/main/java/com/zerobase/cafebom/option/service/dto/OptionAddDto.java
  src/main/java/com/zerobase/cafebom/option/service/dto/OptionDto.java
Labels: new feature, 리뷰 요청

#32 Feat : 관리자 상품 등록,조회,수정,삭제 기능 구현
  build.gradle
  src/main/java/com/zerobase/cafebom/CafeBomApplication.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductController.java
  src/main/java/com/zerobase/cafebom/admin/controller/form/.gitkeep
  src/main/java/com/zerobase/cafebom/admin/controller/form/AdminProductForm.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminProductService.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminProductServiceImpl.java
  src/main/java/com/zerobase/cafebom/admin/service/S3UploaderService.java
  src/main/java/com/zerobase/cafebom/admin/service/dto/.gitkeep
  src/main/java/com/zerobase/cafebom/admin/service/dto/AdminProductDto.java
  src/main/java/com/zerobase/cafebom/config/S3Config.java
  src/main/java/com/zerobase/cafebom/product/domain/.gitkeep
  src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
  src/main/java/com/zerobase/cafebom/product/domain/type/SoldOutStatus.java
  src/main/java/com/zerobase/cafebom/productcategory/domain/entity/ProductCategory.java
Labels: new feature, 리팩토링 중, 리뷰 요청

#48 Fix: 장바구니 엔티티에 주문 상태 컬럼 추가, isOrdered 컬럼 삭제
  src/main/java/com/zerobase/cafebom/cart/domain/entity/.gitkeep
  src/main/java/com/zerobase/cafebom/cart/domain/entity/Cart.java
  src/main/java/com/zerobase/cafebom/cart/domain/entity/type/CartOrderStatus.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersServiceTest.java
Labels: fix feature, 빠른 리뷰 요청

#31 Feat: 주문내역 조회하기 기능 구현
  src/main/java/com/zerobase/cafebom/common/BaseTimeEntity.java
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
  src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
  src/main/java/com/zerobase/cafebom/orders/repository/OrdersRepository.java
  src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
  src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersHisDto.java
  src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersProductDto.java
  src/main/java/com/zerobase/cafebom/ordersproduct/repository/OrdersProductRepository.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersListControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/repository/OrdersRepositoryTest.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersListServiceTest.java
Labels: new feature, 빠른 리뷰 요청, 피드백 반영 중

#50 Rename: 주문 저장 컨트롤러/서비스 테스트코드 클래스명 OrdersAdd~~Test로 변경
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersAddControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersAddServiceTest.java
Labels: refactor, 리뷰 요청

#33 Feat: 주문 상태 변경 기능 완성
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
  src/main/java/com/zerobase/cafebom/orders/controller/form/OrdersElapsedFindForm.java
  src/main/java/com/zerobase/cafebom/orders/controller/form/OrdersStatusModifyForm.java
  src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
  src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
  src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
  src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersStatusModifyDto.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersListControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersStatusControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersStatusServiceTest.java
Labels: new feature, request finished, 리뷰 요청

#37 Feat: 주문 상세보기 기능 구현 완료
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductController.java
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/option/domain/OptionRepository.java
  src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
  src/main/java/com/zerobase/cafebom/product/dto/ProductDetailDto.java
  src/main/java/com/zerobase/cafebom/product/dto/ProductDetailForm.java
  src/main/java/com/zerobase/cafebom/product/service/ProductService.java
  src/main/java/com/zerobase/cafebom/productoptioncategory/domain/ProductOptionCategoryRepository.java
  src/main/java/com/zerobase/cafebom/type/SoldOutStatus.java
  src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
  src/test/java/com/zerobase/cafebom/product/repository/ProductRepositoryTest.java
  src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
  src/test/java/com/zerobase/cafebom/productoptioncategory/repository/ProductOptionCategoryRepositoryTest.java
Labels: new feature, 리뷰 요청

#52 Docs: 배포용 application-prod.yml gitignore에 추가, build.gradle 파일 버전 수정 및 submodule 설정 삭제
  .gitignore
  Dockerfile
  build.gradle
Labels: documentation, 빠른 리뷰 요청

#58 Refactor: 스웨거 UI 전체적으로 정리, 변경된 api endpoint에 따라 테스트코드 변경
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOrdersController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductController.java
  src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
  src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
  src/test/java/com/zerobase/cafebom/admin/controller/AdminOrdersControllerTest.java
  src/test/java/com/zerobase/cafebom/auth/controller/AuthControllerTest.java
  src/test/java/com/zerobase/cafebom/cartoption/domain/CartOptionRepositoryTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersAddControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersListControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersStatusControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/domain/OrdersRepositoryTest.java
  src/test/java/com/zerobase/cafebom/product/domain/ProductRepositoryTest.java
  src/test/java/com/zerobase/cafebom/productoptioncategory/domain/ProductOptionCategoryRepositoryTest.java
Labels: documentation, refactor, 빠른 리뷰 요청

#59 Feat: 리뷰 등록 기능 구현 완료
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/review/controller/.gitkeep
  src/main/java/com/zerobase/cafebom/review/controller/ReviewController.java
  src/main/java/com/zerobase/cafebom/review/controller/form/ReviewAddForm.java
  src/main/java/com/zerobase/cafebom/review/domain/.gitkeep
  src/main/java/com/zerobase/cafebom/review/domain/entity/Review.java
  src/main/java/com/zerobase/cafebom/review/repository/ReviewRepository.java
  src/main/java/com/zerobase/cafebom/review/service/.gitkeep
  src/main/java/com/zerobase/cafebom/review/service/ReviewService.java
  src/main/java/com/zerobase/cafebom/review/service/dto/ReviewAddDto.java
  src/test/java/com/zerobase/cafebom/review/controller/ReviewControllerTest.java
  src/test/java/com/zerobase/cafebom/review/service/ReviewServiceTest.java
Labels: new feature, 빠른 리뷰 요청

#60 Refactor: ErrorCode 파일 HttpStatus static Import 수정
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
Labels: fix feature, 빠른 리뷰 요청

#62 Feat: 장바구니 목록 조회 기능
  src/main/java/com/zerobase/cafebom/cart/controller/.gitkeep
  src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
  src/main/java/com/zerobase/cafebom/cart/domain/Cart.java
  src/main/java/com/zerobase/cafebom/cart/domain/CartRepository.java
  src/main/java/com/zerobase/cafebom/cart/dto/CartListDto.java
  src/main/java/com/zerobase/cafebom/cart/dto/CartListForm.java
  src/main/java/com/zerobase/cafebom/cart/service/.gitkeep
  src/main/java/com/zerobase/cafebom/cart/service/CartService.java
  src/main/java/com/zerobase/cafebom/cartoption/domain/CartOptionRepository.java
  src/main/java/com/zerobase/cafebom/product/dto/ProductDetailDto.java
  src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
  src/test/java/com/zerobase/cafebom/cart/domain/CartRepositoryTest.java
  src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersAddServiceTest.java
Labels: new feature, 리뷰 요청

#51 Feat : 관리자 카테고리 조회, 삭제 기능 추가
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/dto/AdminProductCategoryDto.java
  src/main/java/com/zerobase/cafebom/admin/dto/AdminProductCategoryForm.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminProductCategoryService.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminProductCategoryServiceImpl.java
  src/main/java/com/zerobase/cafebom/productcategory/dto/ProductCategoryDto.java
  src/main/java/com/zerobase/cafebom/productcategory/service/ProductCategoryService.java
  src/main/java/com/zerobase/cafebom/productcategory/service/ProductCategoryServiceImpl.java
Labels: new feature, 리팩토링 중

#61 Feat: 베스트 상품 조회 기능 구현 완료
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/orders/domain/OrdersRepository.java
  src/main/java/com/zerobase/cafebom/ordersproduct/domain/OrdersProduct.java
  src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
  src/main/java/com/zerobase/cafebom/product/dto/BestProductDto.java
  src/main/java/com/zerobase/cafebom/product/dto/BestProductForm.java
  src/main/java/com/zerobase/cafebom/product/service/ProductService.java
  src/test/java/com/zerobase/cafebom/admin/controller/AdminOrdersControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersStatusControllerTest.java
  src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
  src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
Labels: new feature, 빠른 리뷰 요청

#63 Feat : 관리자 옵션 카테고리 등록 기능 추가
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionController.java
  src/main/java/com/zerobase/cafebom/admin/dto/AdminOptionCategoryDto.java
  src/main/java/com/zerobase/cafebom/admin/dto/AdminOptionCategoryForm.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminOptionCategoryService.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminOptionCategoryServiceImpl.java
  src/main/java/com/zerobase/cafebom/optioncategory/controller/.gitkeep
  src/main/java/com/zerobase/cafebom/optioncategory/service/.gitkeep
Labels: new feature, 빠른 리뷰 요청, request finished

#67 Refactor : ErrorCode 수정사항으로 인해 발생한 에러 수정
  src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
Labels: refactor, 빠른 리뷰 요청

#65 Feat : 관리자 옵션 카테고리 삭제, 조회 기능 추가
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/dto/AdminOptionCategoryDto.java
  src/main/java/com/zerobase/cafebom/admin/dto/AdminOptionCategoryForm.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminOptionCategoryService.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminOptionCategoryServiceImpl.java
  src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
  src/test/java/com/zerobase/cafebom/admin/service/AdminOptionCategoryServiceTest.java
Labels: new feature, 빠른 리뷰 요청, request finished

#68 Fix: api 별 접근 권한 스프링 시큐리티 설정 수정, 그에 맞게 테스트코드 수정
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOrdersController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductController.java
  src/main/java/com/zerobase/cafebom/auth/controller/AuthController.java
  src/main/java/com/zerobase/cafebom/auth/service/AuthService.java
  src/main/java/com/zerobase/cafebom/config/PasswordEncoderConfig.java
  src/main/java/com/zerobase/cafebom/member/domain/Member.java
  src/main/java/com/zerobase/cafebom/option/service/OptionService.java
  src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
  src/main/java/com/zerobase/cafebom/security/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/cafebom/security/SecurityConfig.java
  src/main/java/com/zerobase/cafebom/security/SecurityConfiguration.java
  src/main/java/com/zerobase/cafebom/security/TokenProvider.java
  src/test/java/com/zerobase/cafebom/admin/controller/AdminOrdersControllerTest.java
  src/test/java/com/zerobase/cafebom/auth/controller/AuthControllerTest.java
  src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersAddControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersListControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersStatusControllerTest.java
  src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
Labels: bug, 빠른 리뷰 요청

#69 Remove: 레포지토리 테스트코드들 삭제
  src/test/java/com/zerobase/cafebom/cart/domain/CartRepositoryTest.java
  src/test/java/com/zerobase/cafebom/cartoption/domain/CartOptionRepositoryTest.java
  src/test/java/com/zerobase/cafebom/orders/domain/OrdersRepositoryTest.java
  src/test/java/com/zerobase/cafebom/product/domain/ProductRepositoryTest.java
  src/test/java/com/zerobase/cafebom/productoptioncategory/domain/ProductOptionCategoryRepositoryTest.java
  src/test/java/com/zerobase/cafebom/productoptioncategory/repository/ProductOptionCategoryRepositoryTest.java
Labels: refactor

#66 Feat: 상품수량변경, 장바구니조회, 상품삭제 기능 추가
  src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
  src/main/java/com/zerobase/cafebom/cart/controller/form/CartAddForm.java
  src/main/java/com/zerobase/cafebom/cart/domain/Cart.java
  src/main/java/com/zerobase/cafebom/cart/domain/CartRepository.java
  src/main/java/com/zerobase/cafebom/cart/service/CartService.java
  src/main/java/com/zerobase/cafebom/cart/service/dto/CartProductDto.java
  src/main/java/com/zerobase/cafebom/cartoption/domain/CartOption.java
  src/main/java/com/zerobase/cafebom/cartoption/domain/CartOptionRepository.java
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
  src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
Labels: new feature, 피드백 반영 중, 리뷰 요청

#70 Refactor: 리팩토링 체크 목록에 맞게 코드 리팩토링
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
  src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
  src/main/java/com/zerobase/cafebom/product/dto/BestProductForm.java
  src/main/java/com/zerobase/cafebom/product/service/ProductService.java
  src/main/java/com/zerobase/cafebom/type/OrdersCookingTime.java
  src/main/java/com/zerobase/cafebom/type/OrdersReceiptStatus.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersStatusServiceTest.java
  src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
Labels: refactor, 리뷰 요청

#75 Readme: 프로젝트 리드미 완성
  README.md
Labels: documentation, 리뷰 요청

#76 Docs: 스웨거 이너클래스 스키마 표시오류 '@ApiModel' 어노테이션으로 해결
  src/main/java/com/zerobase/cafebom/admin/dto/AdminOptionCategoryForm.java
  src/main/java/com/zerobase/cafebom/admin/dto/AdminProductCategoryForm.java
  src/main/java/com/zerobase/cafebom/auth/dto/SigninForm.java
  src/main/java/com/zerobase/cafebom/option/dto/OptionForm.java
  src/main/java/com/zerobase/cafebom/orders/dto/OrdersAddForm.java
  src/main/java/com/zerobase/cafebom/review/controller/form/ReviewAddForm.java
Labels: bug, documentation, 리뷰 요청

#71 Refactor : 관리자 상품, 옵션, 상품카테고리 리팩토링
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminProductController.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminProductCategoryServiceImpl.java
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/productcategory/domain/ProductCategoryRepository.java
Labels: refactor, 리뷰 요청

#77 Docs: 9.17 버전 배포 완료
  Dockerfile
  README.md
  build.gradle
  src/main/java/com/zerobase/cafebom/config/SwaggerConfig.java
Labels: documentation, 리뷰 요청

#78 Refactor: count라는 컬럼, 변수, 메서드 전부 quantity로 변경
  src/main/java/com/zerobase/cafebom/cart/controller/form/CartAddForm.java
  src/main/java/com/zerobase/cafebom/cart/domain/Cart.java
  src/main/java/com/zerobase/cafebom/cart/dto/CartListDto.java
  src/main/java/com/zerobase/cafebom/cart/dto/CartListForm.java
  src/main/java/com/zerobase/cafebom/cart/service/CartService.java
  src/main/java/com/zerobase/cafebom/cart/service/dto/CartProductDto.java
  src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
  src/main/java/com/zerobase/cafebom/ordersproduct/domain/OrdersProduct.java
  src/main/java/com/zerobase/cafebom/product/service/ProductService.java
  src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
  src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersAddServiceTest.java
  src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
Labels: refactor, 리뷰 요청

#80 Refactor : swagger Authorize 버튼 생성을 위한 기능 추가
  src/main/java/com/zerobase/cafebom/config/SwaggerConfig.java
Labels: fix feature, 리뷰 요청

#72 Refactor: 상품 카테고리 별 상품 목록 조회, 장바구니 목록 조회 리팩토링
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionController.java
  src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
  src/main/java/com/zerobase/cafebom/cart/dto/CartListDto.java
  src/main/java/com/zerobase/cafebom/cart/dto/CartListForm.java
  src/main/java/com/zerobase/cafebom/cart/dto/CartListOptionDto.java
  src/main/java/com/zerobase/cafebom/cart/service/CartService.java
  src/main/java/com/zerobase/cafebom/orders/dto/OrdersHisDto.java
  src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
  src/main/java/com/zerobase/cafebom/product/dto/ProductListForm.java
  src/main/java/com/zerobase/cafebom/product/service/ProductService.java
  src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
  src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
  src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
  src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
Labels: refactor, 리뷰 요청

#82 Refactor: 주문 관련 기능 관리자/사용자 권한 부여, RequestHeader에 사용자 토큰 추가
  src/main/java/com/zerobase/cafebom/admin/controller/AdminOrdersController.java
  src/main/java/com/zerobase/cafebom/admin/service/AdminOrdersService.java
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
  src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
  src/test/java/com/zerobase/cafebom/admin/controller/AdminOrdersControllerTest.java
  src/test/java/com/zerobase/cafebom/admin/service/AdminOrdersServiceTest.java
  src/test/java/com/zerobase/cafebom/orders/controller/OrdersStatusControllerTest.java
  src/test/java/com/zerobase/cafebom/orders/service/OrdersStatusServiceTest.java
Labels: refactor, 리뷰 요청

#81 Fix: 장바구니 목록 조회 기능 버그 해결
  src/main/java/com/zerobase/cafebom/front/cart/domain/CartRepository.java
  src/main/java/com/zerobase/cafebom/front/cart/service/impl/CartService.java
  src/test/java/com/zerobase/cafebom/front/cart/service/CartServiceTest.java
Labels: bug, 리뷰 요청

#84 Refactor : 관리자 권한 기능 부여 어노테이션 추가 및 에러코드 수정
  src/main/java/com/zerobase/cafebom/admin/product/controller/AdminOptionCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/product/controller/AdminOptionController.java
  src/main/java/com/zerobase/cafebom/admin/product/controller/AdminProductCategoryController.java
  src/main/java/com/zerobase/cafebom/admin/product/controller/AdminProductController.java
  src/main/java/com/zerobase/cafebom/admin/product/dto/AdminOptionCategoryForm.java
  src/main/java/com/zerobase/cafebom/admin/product/dto/AdminOptionDto.java
  src/main/java/com/zerobase/cafebom/admin/product/dto/AdminOptionForm.java
  src/main/java/com/zerobase/cafebom/admin/product/dto/AdminProductForm.java
  src/main/java/com/zerobase/cafebom/admin/product/service/AdminOptionService.java
  src/main/java/com/zerobase/cafebom/admin/product/service/impl/AdminOptionServiceImpl.java
  src/main/java/com/zerobase/cafebom/auth/dto/SignupAdminForm.java
  src/main/java/com/zerobase/cafebom/front/product/service/OptionService.java
Labels: refactor, 빠른 리뷰 요청

#88 Refactor: 리팩토링 항목에 따라 Auth 패키지 내 Controller, Service 리팩토링
  src/main/java/com/zerobase/cafebom/auth/controller/AuthController.java
  src/main/java/com/zerobase/cafebom/auth/dto/SigninDto.java
  src/main/java/com/zerobase/cafebom/auth/dto/SigninForm.java
  src/main/java/com/zerobase/cafebom/auth/dto/SignupAdminForm.java
  src/main/java/com/zerobase/cafebom/auth/dto/SignupDto.java
  src/main/java/com/zerobase/cafebom/auth/dto/SignupMemberForm.java
  src/main/java/com/zerobase/cafebom/auth/service/impl/AuthService.java
  src/main/java/com/zerobase/cafebom/common/exception/ExceptionHandler.java
  src/test/java/com/zerobase/cafebom/auth/controller/AuthControllerTest.java
Labels: refactor, 리뷰 요청

#86 Readme: 스프링부트 버전 3.0 오표기, ERD 수정
  Dockerfile
  README.md
  build.gradle
  src/main/java/com/zerobase/cafebom/common/config/SwaggerConfig.java
Labels: documentation, 리뷰 요청
