Repository YesunPark/cafe-bom, pull requests merged in 2023-08, with the labels that each got.

#1 Setting: H2 연결
  src/main/resources/application.yml
Labels: documentation

#2 Feat: Member Entity/Repository/RepositoryTest 완성, BaseTimeEntity 생성
  src/main/java/com/zerobase/CafeBom/common/BaseTimeEntity.java
  src/main/java/com/zerobase/CafeBom/common/JpaAuditingConfig.java
  src/main/java/com/zerobase/CafeBom/exception/.gitkeep
  src/main/java/com/zerobase/CafeBom/user/domain/entity/.gitkeep
  src/main/java/com/zerobase/CafeBom/user/domain/entity/Member.java
  src/main/java/com/zerobase/CafeBom/user/repository/MemberRepository.java
  src/test/java/com/zerobase/CafeBom/user/repository/MemberRepositoryTest.java
Labels: new feature

#3 Feat: Menu Entity/Repository 완성
  src/main/java/com/zerobase/CafeBom/menu/domain/entity/Menu.java
  src/main/java/com/zerobase/CafeBom/menu/repository/MenuRepository.java
  src/test/java/com/zerobase/CafeBom/menu/repository/MenuRepositoryTest.java
Labels: new feature

#8 Feat: 에러 응답 객체 형식을 지정해서 반환할 수 있도록 관련 파일들 추가
  src/main/java/com/zerobase/CafeBom/exception/.gitkeep
  src/main/java/com/zerobase/CafeBom/exception/CustomException.java
  src/main/java/com/zerobase/CafeBom/exception/ExceptionController.java
  src/main/java/com/zerobase/CafeBom/type/ErrorCode.java
Labels: new feature, 리뷰 요청

#7 Feat: Order Entity/Repository/RepositoryTest 완성
  src/main/java/com/zerobase/CafeBom/menu/domain/entity/Menu.java
  src/main/java/com/zerobase/CafeBom/menu/repository/MenuRepository.java
  src/main/java/com/zerobase/CafeBom/order/domain/.gitkeep
  src/main/java/com/zerobase/CafeBom/order/domain/entity/Order.java
  src/main/java/com/zerobase/CafeBom/order/repository/.gitkeep
  src/main/java/com/zerobase/CafeBom/order/repository/OrderRepository.java
  src/main/java/com/zerobase/CafeBom/type/OrderCookingTime.java
  src/main/java/com/zerobase/CafeBom/type/OrderStatus.java
  src/test/java/com/zerobase/CafeBom/order/repository/OrderRepositoryTest.java
Labels: new feature, 리뷰 요청

#9 Rename: Menu관련 파일을 Product로 이름 수정
  src/main/java/com/zerobase/CafeBom/menu/domain/entity/Menu.java
  src/main/java/com/zerobase/CafeBom/menu/repository/MenuRepository.java
  src/main/java/com/zerobase/CafeBom/product/controller/.gitkeep
  src/main/java/com/zerobase/CafeBom/product/controller/dto/.gitkeep
  src/main/java/com/zerobase/CafeBom/product/domain/.gitkeep
  src/main/java/com/zerobase/CafeBom/product/domain/entity/Product.java
  src/main/java/com/zerobase/CafeBom/product/repository/ProductRepository.java
  src/main/java/com/zerobase/CafeBom/product/service/.gitkeep
  src/main/java/com/zerobase/CafeBom/product/service/dto/.gitkeep
  src/main/java/com/zerobase/CafeBom/productOptionCategory/domain/entity/ProductOptionCategory.java
  src/test/java/com/zerobase/CafeBom/menu/repository/MenuRepositoryTest.java
  src/test/java/com/zerobase/CafeBom/product/repository/ProductRepositoryTest.java
Labels: 빠른 리뷰 요청

#4 Feat : Cart Entity
  src/main/java/com/zerobase/CafeBom/cart/controller/.gitkeep
  src/main/java/com/zerobase/CafeBom/cart/domain/.gitkeep
  src/main/java/com/zerobase/CafeBom/cart/domain/entity/.gitkeep
  src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
  src/main/java/com/zerobase/CafeBom/cart/repository/.gitkeep
  src/main/java/com/zerobase/CafeBom/cart/repository/CartRepository.java
  src/main/java/com/zerobase/CafeBom/cart/service/.gitkeep
  src/main/java/com/zerobase/CafeBom/cart/service/dto/.gitkeep
Labels: new feature, 리뷰 요청

#12 Feat: CartOption 엔티티, 레파지토리, 레파지토리 테스트코드 생성
  src/main/java/com/zerobase/CafeBom/cartOption/domain/entity/CartOption.java
  src/main/java/com/zerobase/CafeBom/cartOption/repository/CartOptionRepository.java
  src/test/java/com/zerobase/CafeBom/cartOption/repository/CartOptionRepositoryTest.java
Labels: new feature, 리뷰 요청

#15 Rename: Order 테이블명 변경
  src/main/java/com/zerobase/CafeBom/order/domain/entity/Orders.java
  src/main/java/com/zerobase/CafeBom/order/repository/OrdersRepository.java
  src/main/java/com/zerobase/CafeBom/type/OrdersCookingTime.java
  src/main/java/com/zerobase/CafeBom/type/OrdersStatus.java
  src/test/java/com/zerobase/CafeBom/order/repository/OrdersRepositoryTest.java
Labels: refactor, 리뷰 요청

#18 Refactor: merge 실수로 인한 Order 테이블명, 클래스명 재변경(Order -> Orders)
  src/main/java/com/zerobase/CafeBom/order/repository/OrdersRepository.java
  src/main/java/com/zerobase/CafeBom/type/OrdersCookingTime.java
  src/main/java/com/zerobase/CafeBom/type/OrdersStatus.java
  src/main/java/com/zerobase/cafebom/orders/domain/entity/Order.java
  src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
  src/main/java/com/zerobase/cafebom/orders/repository/OrdersRepository.java
  src/test/java/com/zerobase/CafeBom/order/repository/OrdersRepositoryTest.java
  src/test/java/com/zerobase/cafebom/orders/repository/OrdersRepositoryTest.java
Labels: 빠른 리뷰 요청

#14 Feat: 컨트롤러 DTO validation exceptionController 구현
  src/main/java/com/zerobase/cafebom/exception/ExceptionController.java
Labels: fix feature, 리뷰 요청

#11 Feat : OrdersCart Entity/Repository 완성
  src/main/java/com/zerobase/CafeBom/common/.gitkeep
  src/main/java/com/zerobase/CafeBom/ordercart/controller/.gitkeep
  src/main/java/com/zerobase/CafeBom/ordercart/controller/dto/.gitkeep
  src/main/java/com/zerobase/CafeBom/ordercart/domain/.gitkeep
  src/main/java/com/zerobase/CafeBom/ordercart/repository/.gitkeep
  src/main/java/com/zerobase/CafeBom/ordercart/service/.gitkeep
  src/main/java/com/zerobase/CafeBom/ordercart/service/dto/.gitkeep
  src/main/java/com/zerobase/cafebom/orderscart/domain/entity/OrdersCart.java
  src/main/java/com/zerobase/cafebom/orderscart/repository/OrdersCartRepository.java
  src/test/java/com/zerobase/cafebom/oderscart/repository/OrdersCartRepositoryTest.java
Labels: new feature, 리뷰 요청

#21 Remove: 지워지지 않은 Menu 클래스 삭제
  src/main/java/com/zerobase/cafebom/menu/domain/entity/Menu.java
Labels: documentation, 리뷰 요청

#22 Feat: OrdersProduct, OrdersProductOption 엔티티, 레포지토리 구현
  src/main/java/com/zerobase/cafebom/ordersproduct/domain/entity/OrdersProduct.java
  src/main/java/com/zerobase/cafebom/ordersproduct/repository/OrdersProductRepository.java
  src/main/java/com/zerobase/cafebom/ordersproductoption/domain/entity/OrdersProductOption.java
  src/main/java/com/zerobase/cafebom/ordersproductoption/repository/OrdersProductOptionRepository.java
Labels: new feature, 리뷰 요청

#25 Fix: TokenProvider, AuthService에서 인증정보 추출하는 메서드 수정, 토큰 추출하는 메서드 추가
  src/main/java/com/zerobase/cafebom/member/security/TokenProvider.java
  src/main/java/com/zerobase/cafebom/member/service/AuthService.java
Labels: fix feature, 빠른 리뷰 요청

#23 Refactor : Orders 엔티티 payment 필드 enum으로 변경, enum파일(OrdersPayment) 추가
  src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
  src/main/java/com/zerobase/cafebom/orders/domain/type/Payment.java
Labels: 빠른 리뷰 요청

#24 Fix: security 폴더 위치 변경, "/product/**" 시큐리티 검사에서 제거.
  src/main/java/com/zerobase/cafebom/member/controller/AuthController.java
  src/main/java/com/zerobase/cafebom/member/domain/entity/Member.java
  src/main/java/com/zerobase/cafebom/member/service/AuthService.java
  src/main/java/com/zerobase/cafebom/member/service/dto/SigninDto.java
  src/main/java/com/zerobase/cafebom/security/JwtAuthenticationFilter.java
  src/main/java/com/zerobase/cafebom/security/Role.java
  src/main/java/com/zerobase/cafebom/security/SecurityConfiguration.java
  src/main/java/com/zerobase/cafebom/security/TokenProvider.java
  src/main/java/com/zerobase/cafebom/security/UserAuthenticationFailureHandler.java
  src/test/java/com/zerobase/cafebom/member/controller/AuthControllerTest.java
Labels: fix feature, 리뷰 요청

#26 Feat: OrdersProduct, OrdersProductOption의 일부 컬럼 객체 매핑해제 후 id만 연결
  src/main/java/com/zerobase/cafebom/ordersproduct/domain/entity/OrdersProduct.java
  src/main/java/com/zerobase/cafebom/ordersproductoption/domain/entity/OrdersProductOption.java
Labels: fix feature, 빠른 리뷰 요청

#28 Delete: .DS_Store 파일 삭제
  .DS_Store
  .gitignore
Labels: documentation, 리뷰 요청

#27 Refactor: Orders 엔티티 isCanceled 필드 삭제 후 OrdersReceiptStatus enum타입으로 수정
  src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
  src/main/java/com/zerobase/cafebom/orders/domain/type/OrdersCookingStatus.java
  src/main/java/com/zerobase/cafebom/orders/domain/type/OrdersReceiptStatus.java
Labels: refactor, 빠른 리뷰 요청

#34 Feat : Spring Security Admin 보안관련 기능 추가
  src/main/java/com/zerobase/cafebom/security/SecurityConfiguration.java
Labels: new feature, 빠른 리뷰 요청

#29 Feat: 카테고리 별 상품 조회 기능 구현
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/exception/ExceptionController.java
  src/main/java/com/zerobase/cafebom/product/controller/.gitkeep
  src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
  src/main/java/com/zerobase/cafebom/product/controller/form/.gitkeep
  src/main/java/com/zerobase/cafebom/product/controller/form/ProductListForm.java
  src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
  src/main/java/com/zerobase/cafebom/product/domain/type/SoldOutStatus.java
  src/main/java/com/zerobase/cafebom/product/repository/ProductRepository.java
  src/main/java/com/zerobase/cafebom/product/service/.gitkeep
  src/main/java/com/zerobase/cafebom/product/service/ProductService.java
  src/main/java/com/zerobase/cafebom/product/service/dto/.gitkeep
  src/main/java/com/zerobase/cafebom/product/service/dto/ProductDto.java
  src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
  src/test/java/com/zerobase/cafebom/product/repository/ProductRepositoryTest.java
  src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
Labels: new feature, request finished, 리뷰 요청

#35 Feat: 카카오페이 QR 테스트결제 api, html 화면 구현
  build.gradle
  src/main/java/com/zerobase/cafebom/pay/controller/PayController.java
  src/main/java/com/zerobase/cafebom/pay/service/PayService.java
  src/main/resources/templates/pay.html
Labels: new feature, 리뷰 요청

#41 Refactor: product-list -> product/list로 변경
  src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
  src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
  src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
Labels: refactor, 빠른 리뷰 요청

#45 Setting: build.gradle 에 젠킨스 설정 추가
  Dockerfile
  build.gradle
Labels: documentation, 리뷰 요청
